<div style="margin-left:10px">
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

	<h1>An error occurred</h1>
	<h2><?php echo $this->message ?></h2>

	<?php if (isset($this->exception)): ?>

		<h3>Exception information:</h3>
		<p>
		  <b>Message:</b> <?php echo $this->exception->getMessage() ?>
		</p>

		<h3>Stack trace:</h3>
		<pre><?php echo $this->exception->getTraceAsString() ?>
		</pre>

		<h3>Request Parameters:</h3>
		<pre><?php echo var_export($this->request->getParams(), true) ?>
		</pre>
		<p>
			<a href="<?php echo $this->baseUrl('/ho/index');?>">Back to Bento Localization Portal</a>	
		<p>
		<p>
			<a href="<?php echo $this->baseUrl('/auth/index');?>">Login</a>	
		<p>
	<?php endif ?>	
<?php endif ?>
</div>